PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE shows (id INTEGER, title TEXT NOT NULL, PRIMARY KEY(id));
INSERT INTO shows VALUES(1,'How i met your mother');
INSERT INTO shows VALUES(2,'The Sopranos');
INSERT INTO shows VALUES(3,'Friday Night Lights');
INSERT INTO shows VALUES(4,'Family Guy');
INSERT INTO shows VALUES(5,'New Girl');
INSERT INTO shows VALUES(6,'Friends');
INSERT INTO shows VALUES(7,'Office');
INSERT INTO shows VALUES(8,'Breaking Bad');
INSERT INTO shows VALUES(9,'Modern Family');
INSERT INTO shows VALUES(10,'Office');
INSERT INTO shows VALUES(11,'White Collar');
INSERT INTO shows VALUES(12,'Modern Family');
INSERT INTO shows VALUES(13,'Game of Thrones');
INSERT INTO shows VALUES(14,'the Untamed');
INSERT INTO shows VALUES(15,'The 100');
INSERT INTO shows VALUES(16,'Modern Family');
INSERT INTO shows VALUES(17,'The Office');
INSERT INTO shows VALUES(18,'New Girl');
INSERT INTO shows VALUES(19,'The Office');
INSERT INTO shows VALUES(20,'Avatar: The Last Airbender');
INSERT INTO shows VALUES(21,'Cobra Kai');
INSERT INTO shows VALUES(22,'Sherlock Homes');
INSERT INTO shows VALUES(23,'New Girl');
INSERT INTO shows VALUES(24,'arrow');
INSERT INTO shows VALUES(25,'Grace and Frankie');
INSERT INTO shows VALUES(26,'The Great British Baking Show');
INSERT INTO shows VALUES(27,'The Mentalist');
INSERT INTO shows VALUES(28,'Brooklyn-99');
INSERT INTO shows VALUES(29,'Avatar The Last Airbender ');
INSERT INTO shows VALUES(30,'Parks and Rec');
INSERT INTO shows VALUES(31,'Archer');
INSERT INTO shows VALUES(32,'Friends');
INSERT INTO shows VALUES(33,'The Simpsons');
INSERT INTO shows VALUES(34,'Avatar The Last Airbender');
INSERT INTO shows VALUES(35,'The Flash');
INSERT INTO shows VALUES(36,'Avatar the Last Airbender ');
INSERT INTO shows VALUES(37,'New Girl');
INSERT INTO shows VALUES(38,'Stranger Things');
INSERT INTO shows VALUES(39,'Squid Game');
INSERT INTO shows VALUES(40,'Friends ');
INSERT INTO shows VALUES(41,'Community');
INSERT INTO shows VALUES(42,'Curb Your Enthusiasm');
INSERT INTO shows VALUES(43,'Hannah Montana ');
INSERT INTO shows VALUES(44,'The Simpsons');
INSERT INTO shows VALUES(45,'The Good Place');
INSERT INTO shows VALUES(46,'Band of Brothers');
INSERT INTO shows VALUES(47,'Jeopardy');
INSERT INTO shows VALUES(48,'The Office');
INSERT INTO shows VALUES(49,'The Good Place');
INSERT INTO shows VALUES(50,'Violet Evergarden');
INSERT INTO shows VALUES(51,'Avatar the Last Airbender');
INSERT INTO shows VALUES(52,'Game of Thrones');
INSERT INTO shows VALUES(53,'Breaking Bad');
INSERT INTO shows VALUES(54,'Criminal Minds');
INSERT INTO shows VALUES(55,'Shark Tank');
INSERT INTO shows VALUES(56,'Star Trek: The Next Generation');
INSERT INTO shows VALUES(57,'Squid Game');
INSERT INTO shows VALUES(58,'White Collar');
INSERT INTO shows VALUES(59,'Parks and Recreation ');
INSERT INTO shows VALUES(60,'Mad Men');
INSERT INTO shows VALUES(61,'Friends');
INSERT INTO shows VALUES(62,'South Park');
INSERT INTO shows VALUES(63,'The Office ');
INSERT INTO shows VALUES(64,'Norsemen');
INSERT INTO shows VALUES(65,'The West Wing');
INSERT INTO shows VALUES(66,'Regular Show');
INSERT INTO shows VALUES(67,'Ted Lasso');
INSERT INTO shows VALUES(68,'The Wire');
INSERT INTO shows VALUES(69,'Lost');
INSERT INTO shows VALUES(70,'The Office');
INSERT INTO shows VALUES(71,'Breaking Bad');
INSERT INTO shows VALUES(72,'community');
INSERT INTO shows VALUES(73,'Queen’s Gambit');
INSERT INTO shows VALUES(74,'Community');
INSERT INTO shows VALUES(75,'Friends');
INSERT INTO shows VALUES(76,'How I Met Your Mother');
INSERT INTO shows VALUES(77,'Six Flying Dragons');
INSERT INTO shows VALUES(78,'Gilmore Girls');
INSERT INTO shows VALUES(79,'Reba');
INSERT INTO shows VALUES(80,'friends');
INSERT INTO shows VALUES(81,'Evacuate Earth');
INSERT INTO shows VALUES(82,'Friends');
INSERT INTO shows VALUES(83,'The Flash');
INSERT INTO shows VALUES(84,'The Office');
INSERT INTO shows VALUES(85,'Supernatural ');
INSERT INTO shows VALUES(86,'Peaky Blinders');
INSERT INTO shows VALUES(87,'Game of Thrones');
INSERT INTO shows VALUES(88,'Game of Thrones');
INSERT INTO shows VALUES(89,'Community');
INSERT INTO shows VALUES(90,'Breaking Bad');
INSERT INTO shows VALUES(91,'Community');
INSERT INTO shows VALUES(92,'The Office');
INSERT INTO shows VALUES(93,'The Good Place');
INSERT INTO shows VALUES(94,'The Office');
INSERT INTO shows VALUES(95,'You');
INSERT INTO shows VALUES(96,'Community');
INSERT INTO shows VALUES(97,'Grey''s Anatomy');
INSERT INTO shows VALUES(98,'Breaking Bad');
INSERT INTO shows VALUES(99,'The Crown');
INSERT INTO shows VALUES(100,'Arrested Development');
INSERT INTO shows VALUES(101,'Avatar: The Last Airbender');
INSERT INTO shows VALUES(102,'Black Mirror');
INSERT INTO shows VALUES(103,'Friends');
INSERT INTO shows VALUES(104,'Saturday Night Live');
INSERT INTO shows VALUES(105,'How I Met Your Mother');
INSERT INTO shows VALUES(106,'The Office');
INSERT INTO shows VALUES(107,'the bachelorette');
INSERT INTO shows VALUES(108,'The CROWN');
INSERT INTO shows VALUES(109,'Law and order');
INSERT INTO shows VALUES(110,'B99');
INSERT INTO shows VALUES(111,'GoT');
INSERT INTO shows VALUES(112,'Sherlock');
INSERT INTO shows VALUES(113,'WandaVision');
INSERT INTO shows VALUES(114,'Stranger Things');
INSERT INTO shows VALUES(115,'The Good Place');
INSERT INTO shows VALUES(116,'adventure time');
INSERT INTO shows VALUES(117,'Parks and Rec');
INSERT INTO shows VALUES(118,'squid game');
INSERT INTO shows VALUES(119,'Yellowstone');
INSERT INTO shows VALUES(120,'Brooklyn Nine-Nine');
INSERT INTO shows VALUES(121,'criminal minds');
INSERT INTO shows VALUES(122,'The Haunting of Hill House');
INSERT INTO shows VALUES(123,'Avatar');
INSERT INTO shows VALUES(124,'the office');
INSERT INTO shows VALUES(125,'The Office');
INSERT INTO shows VALUES(126,'Game Of Thrones');
INSERT INTO shows VALUES(127,'The Originals');
INSERT INTO shows VALUES(128,'family guy');
INSERT INTO shows VALUES(129,'Last Week Tonight with John Oliver');
INSERT INTO shows VALUES(130,'Community');
INSERT INTO shows VALUES(131,'WandaVision');
INSERT INTO shows VALUES(132,'billions');
INSERT INTO shows VALUES(133,'ThE OffiCE');
INSERT INTO shows VALUES(134,'Friends');
INSERT INTO shows VALUES(135,'The Office');
INSERT INTO shows VALUES(136,'Top Gear');
INSERT INTO shows VALUES(137,'Six Flying Dragons');
INSERT INTO shows VALUES(138,'New Amsterdam');
INSERT INTO shows VALUES(139,'Game of Thrones');
INSERT INTO shows VALUES(140,'Blue Mountain State');
INSERT INTO shows VALUES(141,'Community');
INSERT INTO shows VALUES(142,'Its Always Sunny in Philidelphia');
INSERT INTO shows VALUES(143,'Thevoffice');
INSERT INTO shows VALUES(144,'Atlanta');
INSERT INTO shows VALUES(145,'Good Omens');
INSERT INTO shows VALUES(146,'The Big Bang Theory');
INSERT INTO shows VALUES(147,'Grey''s anatomy ');
INSERT INTO shows VALUES(148,'Gilmore girls');
INSERT INTO shows VALUES(149,'Avatar: The Last Airbender');
INSERT INTO shows VALUES(150,'Avatar the Last Airbender');
INSERT INTO shows VALUES(151,'Hunter X Hunter');
INSERT INTO shows VALUES(152,'Brooklyn Nine-Nine');
INSERT INTO shows VALUES(153,'sherlock holmes ');
INSERT INTO shows VALUES(154,'Anne With An E');
INSERT INTO shows VALUES(155,'Money Heist');
INSERT INTO shows VALUES(156,'Succession');
INSERT INTO shows VALUES(157,'Silicon Valley');
CREATE TABLE genres (show_id INTEGER, genre TEXT NOT NULL, FOREIGN KEY(show_id) REFERENCES shows(id));
INSERT INTO genres VALUES(1,'Comedy');
INSERT INTO genres VALUES(2,'Comedy');
INSERT INTO genres VALUES(2,'Crime');
INSERT INTO genres VALUES(2,'Drama');
INSERT INTO genres VALUES(2,'Horror');
INSERT INTO genres VALUES(2,'Sci-Fi');
INSERT INTO genres VALUES(2,'Talk-Show');
INSERT INTO genres VALUES(2,'Thriller');
INSERT INTO genres VALUES(3,'Drama');
INSERT INTO genres VALUES(3,'Family');
INSERT INTO genres VALUES(3,'Sport');
INSERT INTO genres VALUES(4,'Animation');
INSERT INTO genres VALUES(4,'Comedy');
INSERT INTO genres VALUES(5,'Comedy');
INSERT INTO genres VALUES(6,'Comedy');
INSERT INTO genres VALUES(7,'Comedy');
INSERT INTO genres VALUES(8,'Crime');
INSERT INTO genres VALUES(8,'Drama');
INSERT INTO genres VALUES(9,'Comedy');
INSERT INTO genres VALUES(10,'Comedy');
INSERT INTO genres VALUES(11,'Action');
INSERT INTO genres VALUES(11,'Crime');
INSERT INTO genres VALUES(11,'Drama');
INSERT INTO genres VALUES(12,'Comedy');
INSERT INTO genres VALUES(12,'Family');
INSERT INTO genres VALUES(13,'Action');
INSERT INTO genres VALUES(13,'Adventure');
INSERT INTO genres VALUES(13,'Drama');
INSERT INTO genres VALUES(13,'Fantasy');
INSERT INTO genres VALUES(13,'Thriller');
INSERT INTO genres VALUES(13,'War');
INSERT INTO genres VALUES(14,'Action');
INSERT INTO genres VALUES(14,'Drama');
INSERT INTO genres VALUES(14,'Fantasy');
INSERT INTO genres VALUES(14,'History');
INSERT INTO genres VALUES(14,'Romance');
INSERT INTO genres VALUES(15,'Action');
INSERT INTO genres VALUES(15,'Sci-Fi');
INSERT INTO genres VALUES(16,'Comedy');
INSERT INTO genres VALUES(16,'Family');
INSERT INTO genres VALUES(17,'Comedy');
INSERT INTO genres VALUES(18,'Comedy');
INSERT INTO genres VALUES(19,'Comedy');
INSERT INTO genres VALUES(20,'Adventure');
INSERT INTO genres VALUES(20,'Animation');
INSERT INTO genres VALUES(21,'Action');
INSERT INTO genres VALUES(21,'Sport');
INSERT INTO genres VALUES(22,'Crime');
INSERT INTO genres VALUES(22,'Drama');
INSERT INTO genres VALUES(22,'Mystery');
INSERT INTO genres VALUES(23,'Comedy');
INSERT INTO genres VALUES(24,'Action');
INSERT INTO genres VALUES(24,'Crime');
INSERT INTO genres VALUES(24,'Fantasy');
INSERT INTO genres VALUES(25,'Comedy');
INSERT INTO genres VALUES(25,'Romance');
INSERT INTO genres VALUES(26,'Game-Show');
INSERT INTO genres VALUES(27,'Crime');
INSERT INTO genres VALUES(27,'Mystery');
INSERT INTO genres VALUES(28,'Action');
INSERT INTO genres VALUES(28,'Comedy');
INSERT INTO genres VALUES(28,'Crime');
INSERT INTO genres VALUES(29,'Action');
INSERT INTO genres VALUES(29,'Adventure');
INSERT INTO genres VALUES(29,'Animation');
INSERT INTO genres VALUES(29,'Comedy');
INSERT INTO genres VALUES(29,'Family');
INSERT INTO genres VALUES(29,'Fantasy');
INSERT INTO genres VALUES(30,'Comedy');
INSERT INTO genres VALUES(31,'Action');
INSERT INTO genres VALUES(31,'Animation');
INSERT INTO genres VALUES(31,'Comedy');
INSERT INTO genres VALUES(32,'Comedy');
INSERT INTO genres VALUES(33,'Comedy');
INSERT INTO genres VALUES(34,'Action');
INSERT INTO genres VALUES(34,'Animation');
INSERT INTO genres VALUES(34,'Crime');
INSERT INTO genres VALUES(35,'Action');
INSERT INTO genres VALUES(35,'Crime');
INSERT INTO genres VALUES(36,'Action');
INSERT INTO genres VALUES(36,'Animation');
INSERT INTO genres VALUES(36,'Fantasy');
INSERT INTO genres VALUES(37,'Comedy');
INSERT INTO genres VALUES(38,'Action');
INSERT INTO genres VALUES(38,'Adventure');
INSERT INTO genres VALUES(39,'Action');
INSERT INTO genres VALUES(39,'Adventure');
INSERT INTO genres VALUES(39,'Drama');
INSERT INTO genres VALUES(39,'Thriller');
INSERT INTO genres VALUES(40,'Comedy');
INSERT INTO genres VALUES(41,'Comedy');
INSERT INTO genres VALUES(42,'Comedy');
INSERT INTO genres VALUES(43,'Comedy');
INSERT INTO genres VALUES(43,'Family');
INSERT INTO genres VALUES(44,'Comedy');
INSERT INTO genres VALUES(45,'Comedy');
INSERT INTO genres VALUES(46,'Action');
INSERT INTO genres VALUES(46,'Biography');
INSERT INTO genres VALUES(46,'Documentary');
INSERT INTO genres VALUES(46,'Drama');
INSERT INTO genres VALUES(46,'History');
INSERT INTO genres VALUES(46,'War');
INSERT INTO genres VALUES(47,'Game-Show');
INSERT INTO genres VALUES(48,'Comedy');
INSERT INTO genres VALUES(49,'Comedy');
INSERT INTO genres VALUES(49,'Fantasy');
INSERT INTO genres VALUES(50,'Animation');
INSERT INTO genres VALUES(50,'Drama');
INSERT INTO genres VALUES(51,'Adventure');
INSERT INTO genres VALUES(51,'Comedy');
INSERT INTO genres VALUES(51,'Family');
INSERT INTO genres VALUES(52,'Action');
INSERT INTO genres VALUES(52,'Adventure');
INSERT INTO genres VALUES(52,'Drama');
INSERT INTO genres VALUES(53,'Action');
INSERT INTO genres VALUES(53,'Crime');
INSERT INTO genres VALUES(53,'Drama');
INSERT INTO genres VALUES(53,'Thriller');
INSERT INTO genres VALUES(54,'Crime');
INSERT INTO genres VALUES(55,'Family');
INSERT INTO genres VALUES(56,'Sci-Fi');
INSERT INTO genres VALUES(57,'Action');
INSERT INTO genres VALUES(57,'Horror');
INSERT INTO genres VALUES(57,'Thriller');
INSERT INTO genres VALUES(58,'Crime');
INSERT INTO genres VALUES(58,'Drama');
INSERT INTO genres VALUES(59,'Comedy');
INSERT INTO genres VALUES(59,'Documentary');
INSERT INTO genres VALUES(60,'Drama');
INSERT INTO genres VALUES(61,'Comedy');
INSERT INTO genres VALUES(62,'Comedy');
INSERT INTO genres VALUES(63,'Comedy');
INSERT INTO genres VALUES(64,'Adventure');
INSERT INTO genres VALUES(64,'Comedy');
INSERT INTO genres VALUES(64,'History');
INSERT INTO genres VALUES(65,'Drama');
INSERT INTO genres VALUES(66,'Comedy');
INSERT INTO genres VALUES(67,'Comedy');
INSERT INTO genres VALUES(68,'Crime');
INSERT INTO genres VALUES(68,'Drama');
INSERT INTO genres VALUES(69,'Action');
INSERT INTO genres VALUES(69,'Adventure');
INSERT INTO genres VALUES(69,'Fantasy');
INSERT INTO genres VALUES(69,'Sci-Fi');
INSERT INTO genres VALUES(70,'Comedy');
INSERT INTO genres VALUES(71,'Action');
INSERT INTO genres VALUES(72,'Comedy');
INSERT INTO genres VALUES(73,'Drama');
INSERT INTO genres VALUES(73,'Thriller');
INSERT INTO genres VALUES(74,'Comedy');
INSERT INTO genres VALUES(75,'Comedy');
INSERT INTO genres VALUES(76,'Comedy');
INSERT INTO genres VALUES(77,'Action');
INSERT INTO genres VALUES(77,'Drama');
INSERT INTO genres VALUES(77,'History');
INSERT INTO genres VALUES(78,'Family');
INSERT INTO genres VALUES(78,'Horror');
INSERT INTO genres VALUES(78,'Romance');
INSERT INTO genres VALUES(79,'Comedy');
INSERT INTO genres VALUES(80,'Comedy');
INSERT INTO genres VALUES(81,'Sci-Fi');
INSERT INTO genres VALUES(82,'Comedy');
INSERT INTO genres VALUES(83,'Sci-Fi');
INSERT INTO genres VALUES(84,'Animation');
INSERT INTO genres VALUES(84,'Comedy');
INSERT INTO genres VALUES(84,'Sci-Fi');
INSERT INTO genres VALUES(85,'Action');
INSERT INTO genres VALUES(85,'Drama');
INSERT INTO genres VALUES(85,'Fantasy');
INSERT INTO genres VALUES(85,'Horror');
INSERT INTO genres VALUES(85,'Mystery');
INSERT INTO genres VALUES(86,'Action');
INSERT INTO genres VALUES(86,'Adventure');
INSERT INTO genres VALUES(86,'Crime');
INSERT INTO genres VALUES(86,'Drama');
INSERT INTO genres VALUES(86,'History');
INSERT INTO genres VALUES(87,'Action');
INSERT INTO genres VALUES(87,'Adventure');
INSERT INTO genres VALUES(87,'Comedy');
INSERT INTO genres VALUES(87,'Drama');
INSERT INTO genres VALUES(87,'Family');
INSERT INTO genres VALUES(87,'Fantasy');
INSERT INTO genres VALUES(87,'History');
INSERT INTO genres VALUES(87,'Horror');
INSERT INTO genres VALUES(87,'Musical');
INSERT INTO genres VALUES(87,'Mystery');
INSERT INTO genres VALUES(87,'Romance');
INSERT INTO genres VALUES(87,'Thriller');
INSERT INTO genres VALUES(87,'War');
INSERT INTO genres VALUES(88,'Action');
INSERT INTO genres VALUES(88,'Drama');
INSERT INTO genres VALUES(88,'Family');
INSERT INTO genres VALUES(88,'Fantasy');
INSERT INTO genres VALUES(88,'War');
INSERT INTO genres VALUES(89,'Comedy');
INSERT INTO genres VALUES(90,'Crime');
INSERT INTO genres VALUES(91,'Comedy');
INSERT INTO genres VALUES(92,'Comedy');
INSERT INTO genres VALUES(92,'Drama');
INSERT INTO genres VALUES(93,'Adventure');
INSERT INTO genres VALUES(93,'Comedy');
INSERT INTO genres VALUES(93,'Drama');
INSERT INTO genres VALUES(94,'Comedy');
INSERT INTO genres VALUES(95,'Drama');
INSERT INTO genres VALUES(95,'Thriller');
INSERT INTO genres VALUES(96,'Comedy');
INSERT INTO genres VALUES(97,'Drama');
INSERT INTO genres VALUES(98,'Action');
INSERT INTO genres VALUES(98,'Comedy');
INSERT INTO genres VALUES(98,'Crime');
INSERT INTO genres VALUES(99,'Comedy');
INSERT INTO genres VALUES(100,'Comedy');
INSERT INTO genres VALUES(101,'Action');
INSERT INTO genres VALUES(101,'Adventure');
INSERT INTO genres VALUES(101,'Animation');
INSERT INTO genres VALUES(101,'Fantasy');
INSERT INTO genres VALUES(102,'Action');
INSERT INTO genres VALUES(102,'Adventure');
INSERT INTO genres VALUES(102,'Animation');
INSERT INTO genres VALUES(102,'Biography');
INSERT INTO genres VALUES(102,'Comedy');
INSERT INTO genres VALUES(102,'Crime');
INSERT INTO genres VALUES(102,'Documentary');
INSERT INTO genres VALUES(102,'Drama');
INSERT INTO genres VALUES(102,'Family');
INSERT INTO genres VALUES(102,'Fantasy');
INSERT INTO genres VALUES(102,'Game-Show');
INSERT INTO genres VALUES(102,'History');
INSERT INTO genres VALUES(102,'Horror');
INSERT INTO genres VALUES(102,'Music');
INSERT INTO genres VALUES(102,'Musical');
INSERT INTO genres VALUES(102,'Mystery');
INSERT INTO genres VALUES(102,'News');
INSERT INTO genres VALUES(102,'Reality-TV');
INSERT INTO genres VALUES(102,'Romance');
INSERT INTO genres VALUES(102,'Sci-Fi');
INSERT INTO genres VALUES(102,'Short');
INSERT INTO genres VALUES(102,'Sport');
INSERT INTO genres VALUES(102,'Talk-Show');
INSERT INTO genres VALUES(102,'Thriller');
INSERT INTO genres VALUES(102,'War');
INSERT INTO genres VALUES(102,'Western');
INSERT INTO genres VALUES(103,'Comedy');
INSERT INTO genres VALUES(104,'Comedy');
INSERT INTO genres VALUES(105,'Comedy');
INSERT INTO genres VALUES(106,'Comedy');
INSERT INTO genres VALUES(107,'Reality-TV');
INSERT INTO genres VALUES(107,'Romance');
INSERT INTO genres VALUES(108,'Drama');
INSERT INTO genres VALUES(109,'Crime');
INSERT INTO genres VALUES(109,'Drama');
INSERT INTO genres VALUES(109,'Mystery');
INSERT INTO genres VALUES(109,'Thriller');
INSERT INTO genres VALUES(110,'Comedy');
INSERT INTO genres VALUES(111,'Action');
INSERT INTO genres VALUES(112,'Mystery');
INSERT INTO genres VALUES(113,'Action');
INSERT INTO genres VALUES(113,'Comedy');
INSERT INTO genres VALUES(113,'Drama');
INSERT INTO genres VALUES(113,'Thriller');
INSERT INTO genres VALUES(114,'Action');
INSERT INTO genres VALUES(114,'Adventure');
INSERT INTO genres VALUES(114,'Sci-Fi');
INSERT INTO genres VALUES(115,'Comedy');
INSERT INTO genres VALUES(115,'Family');
INSERT INTO genres VALUES(115,'Fantasy');
INSERT INTO genres VALUES(116,'Adventure');
INSERT INTO genres VALUES(116,'Drama');
INSERT INTO genres VALUES(116,'Romance');
INSERT INTO genres VALUES(117,'Comedy');
INSERT INTO genres VALUES(118,'Action');
INSERT INTO genres VALUES(118,'Drama');
INSERT INTO genres VALUES(118,'Game-Show');
INSERT INTO genres VALUES(118,'Horror');
INSERT INTO genres VALUES(118,'Mystery');
INSERT INTO genres VALUES(118,'Thriller');
INSERT INTO genres VALUES(119,'Western');
INSERT INTO genres VALUES(120,'Comedy');
INSERT INTO genres VALUES(120,'Crime');
INSERT INTO genres VALUES(121,'Crime');
INSERT INTO genres VALUES(122,'Horror');
INSERT INTO genres VALUES(123,'Action');
INSERT INTO genres VALUES(123,'Animation');
INSERT INTO genres VALUES(123,'Fantasy');
INSERT INTO genres VALUES(124,'Comedy');
INSERT INTO genres VALUES(125,'Comedy');
INSERT INTO genres VALUES(126,'Thriller');
INSERT INTO genres VALUES(127,'Drama');
INSERT INTO genres VALUES(128,'Comedy');
INSERT INTO genres VALUES(129,'Comedy');
INSERT INTO genres VALUES(129,'News');
INSERT INTO genres VALUES(129,'Talk-Show');
INSERT INTO genres VALUES(130,'Comedy');
INSERT INTO genres VALUES(131,'Action');
INSERT INTO genres VALUES(131,'Fantasy');
INSERT INTO genres VALUES(131,'Sci-Fi');
INSERT INTO genres VALUES(132,'Comedy');
INSERT INTO genres VALUES(132,'Drama');
INSERT INTO genres VALUES(133,'Comedy');
INSERT INTO genres VALUES(134,'Comedy');
INSERT INTO genres VALUES(134,'Family');
INSERT INTO genres VALUES(135,'Documentary');
INSERT INTO genres VALUES(136,'Action');
INSERT INTO genres VALUES(136,'Adventure');
INSERT INTO genres VALUES(136,'Comedy');
INSERT INTO genres VALUES(136,'Documentary');
INSERT INTO genres VALUES(136,'Family');
INSERT INTO genres VALUES(137,'Action');
INSERT INTO genres VALUES(137,'Drama');
INSERT INTO genres VALUES(137,'History');
INSERT INTO genres VALUES(138,'Drama');
INSERT INTO genres VALUES(139,'Fantasy');
INSERT INTO genres VALUES(139,'Thriller');
INSERT INTO genres VALUES(139,'War');
INSERT INTO genres VALUES(140,'Action');
INSERT INTO genres VALUES(140,'Comedy');
INSERT INTO genres VALUES(140,'Sport');
INSERT INTO genres VALUES(141,'Action');
INSERT INTO genres VALUES(141,'Adventure');
INSERT INTO genres VALUES(141,'Animation');
INSERT INTO genres VALUES(141,'Comedy');
INSERT INTO genres VALUES(141,'Crime');
INSERT INTO genres VALUES(141,'Documentary');
INSERT INTO genres VALUES(141,'Drama');
INSERT INTO genres VALUES(141,'Family');
INSERT INTO genres VALUES(141,'Fantasy');
INSERT INTO genres VALUES(141,'Game-Show');
INSERT INTO genres VALUES(141,'History');
INSERT INTO genres VALUES(141,'Horror');
INSERT INTO genres VALUES(141,'Music');
INSERT INTO genres VALUES(141,'Musical');
INSERT INTO genres VALUES(141,'Mystery');
INSERT INTO genres VALUES(141,'News');
INSERT INTO genres VALUES(141,'Romance');
INSERT INTO genres VALUES(141,'Sci-Fi');
INSERT INTO genres VALUES(141,'Sport');
INSERT INTO genres VALUES(141,'Talk-Show');
INSERT INTO genres VALUES(141,'Thriller');
INSERT INTO genres VALUES(141,'War');
INSERT INTO genres VALUES(141,'Western');
INSERT INTO genres VALUES(142,'Comedy');
INSERT INTO genres VALUES(142,'Drama');
INSERT INTO genres VALUES(143,'Comedy');
INSERT INTO genres VALUES(144,'Drama');
INSERT INTO genres VALUES(145,'Comedy');
INSERT INTO genres VALUES(145,'Drama');
INSERT INTO genres VALUES(145,'Fantasy');
INSERT INTO genres VALUES(145,'Sci-Fi');
INSERT INTO genres VALUES(146,'Comedy');
INSERT INTO genres VALUES(147,'Drama');
INSERT INTO genres VALUES(148,'Comedy');
INSERT INTO genres VALUES(148,'Drama');
INSERT INTO genres VALUES(149,'Action');
INSERT INTO genres VALUES(149,'Animation');
INSERT INTO genres VALUES(150,'Adventure');
INSERT INTO genres VALUES(150,'Comedy');
INSERT INTO genres VALUES(150,'Drama');
INSERT INTO genres VALUES(150,'Family');
INSERT INTO genres VALUES(150,'Fantasy');
INSERT INTO genres VALUES(151,'Action');
INSERT INTO genres VALUES(151,'Adventure');
INSERT INTO genres VALUES(151,'Animation');
INSERT INTO genres VALUES(152,'Comedy');
INSERT INTO genres VALUES(152,'Crime');
INSERT INTO genres VALUES(153,'Crime');
INSERT INTO genres VALUES(153,'Drama');
INSERT INTO genres VALUES(153,'Mystery');
INSERT INTO genres VALUES(154,'Drama');
INSERT INTO genres VALUES(155,'Action');
INSERT INTO genres VALUES(155,'Adventure');
INSERT INTO genres VALUES(155,'Crime');
INSERT INTO genres VALUES(155,'Horror');
INSERT INTO genres VALUES(155,'Mystery');
INSERT INTO genres VALUES(155,'Sci-Fi');
INSERT INTO genres VALUES(155,'Thriller');
INSERT INTO genres VALUES(155,'War');
INSERT INTO genres VALUES(156,'Drama');
INSERT INTO genres VALUES(157,'Comedy');
COMMIT;

CREATE TABLE student_house (
    id INTEGER,
    house TEXT,
    PRIMARY KEY(id),
    stu_id INT FOREIGN KEY REFERENCES student_name(id)
);